Repository startersclan/docker-steamcmd, pull requests merged in 2023-11, with the labels that each got.

#54 Refactor (dockerfile): Use `i386` syntax for all `i386` packages
  variants/git/Dockerfile
Labels: refactor

#55 Feature: Bump `ubuntu` base image to `focal-20231003`
  .github/workflows/ci-master-pr.yml
  build.sh
Labels: feature

#57 Enhancement: Add network and text tools in `git` variant
  variants/git/Dockerfile
Labels: enhancement
